#Herramienta con el fin de tener una post sesion al doxxing para poder atacar mediante fuerza bruta creando un diccionario con 
#DatosWL a la empresa Que se esta auditando, no me hago responsable del uso fuera de la ley o parametros de acuerdos privados 
# o cualquier fin que sea vulnerar sin permiso lo que sea.
#la herramienta esta creada con el unico fin, vulnerar servidores online o offline.
#todas las dudas en el grupo de la comunidad de Error404 si eres usuario: https://t.me/error404notfounda
#si quieres colaborar con el proyecto contacta alguno de los organizadores de Error404 ellos te atenderan.
#creador: K, administrador de la comunidad Error404.
#visita en nuestra redes sociales ayudanos con tu like...
#-----------------------------------------------------------------------------------------------------------------
#Visita nuestra canal de youtube
#https://www.youtube.com/channel/UC9ZtujTcMuBcKsV4-4G9Zxg
#-----------------------------------------------------------------------------------------------------------------
#Visita nuestra cuenta de Facebook
#https://www.facebook.com/error4o4.org
#-----------------------------------------------------------------------------------------------------------------
#También estamos en Twitter
#https://twitter.com/error4o4org
#-----------------------------------------------------------------------------------------------------------------
#Visita nuestra cuenta de GitHub https://github.com/error404-notfound
#-----------------------------------------------------------------------------------------------------------------
#Cuenta PayPal para sus donativo
#https://www.paypal.me/error404notjavic
#-----------------------------------------------------------------------------------------------------------------
print("")
print("       ·▄▄▄▄   ▄▄▄· ▄▄▄▄▄      .▄▄ · ▄▄▌ ▐ ▄▌▄▄▌  ")
print("        ██▪ ██ ▐█ ▀█ •██  ▪     ▐█ ▀. ██· █▌▐███•  ")
print("        ▐█· ▐█▌▄█▀▀█  ▐█.▪ ▄█▀▄ ▄▀▀▀█▄██▪▐█▐▐▌██▪  ")
print("        ██. ██ ▐█ ▪▐▌ ▐█▌·▐█▌.▐▌▐█▄▪▐█▐█▌██▐█▌▐█▌▐▌")
print("        ▀▀▀▀▀•  ▀  ▀  ▀▀▀  ▀█▄▀▪ ▀▀▀▀  ▀▀▀▀ ▀▪.▀▀▀ ")
print("       POST-DOXXING > https://t.me/error404notfounda")
print("")
archivo=open("DiccionarioE404.txt","a")
a=input("  > Ingrese primer nombre: ")
b=input("  > Ingrese segundo nombre: ")
c=input("  > Ingrese tercer nombre: ")
d=input("  > Ingrese primer apellido: ")
e=input("  > Ingrese segundo apellido: ")
f=input("  > Dia de nacimiento: ")
g=input("  > Mes de nacimiento: ")
h=input("  > Año de nacimiento: ")
i=input("  > Mascota o ex mascota: ")
j=input("  > Dia de nacimiento de su mascota o ex: ")
k=input("  > Mes de nacimiento de su mascota o ex: ")
l=input("  > Año de nacimiento de su mascota o ex: ")
m=input("  > Ingrese el nombre de la pareja o ex: ")
n=input("  > Dia de nacimiento de su pareja o ex: ")
o=input("  > Mes de nacimiento de su pareja o ex: ")
p=input("  > Año de nacimiento de su pareja o ex: ")
q=input("  > Deporte favorito: ")
r=input("  > Hijo menor: ")
s=input("  > Hijo entre medio: ")
t=input("  > Hijo mayor: ")
u=input("  > Pais: ")
w=input("  > Fecha importante: ")
x=input("  > Numeros favoritos: ")
y=input("  > Cantante preferido: ")
z=input("  > Persona de su entorno: ")
hermano=input("  > Ingrese el nombre de su 1er hermano: ")
hermanodos=input("  > Ingrese el nombre de su 2do hermano: ")
hermanotres=input("  > Ingrese el nombre de su 3er hermano: ")
alturaDeLaCasa=input("  > Ingrese la altura de su vivienda: ")
numero=input("  > Numero telefonico: ")
numeromadre=input("  > Numero telefonico de la madre: ")
numeropadre=input("  > Numero telefonico de el padre: ")
datos=input("  > Password que vos creas: ")
archivo.write(a)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(b)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(c)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(d)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(e)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(g)
archivo.write(f)
archivo.write(h)
archivo.write("\n")
archivo.write(h)
archivo.write(f)
archivo.write(g)
archivo.write("\n")
archivo.write(h)
archivo.write(g)
archivo.write(f)
archivo.write("\n")
archivo.write(i)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(j)
archivo.write(k)
archivo.write(l)
archivo.write("\n")
archivo.write(k)
archivo.write(j)
archivo.write(l)
archivo.write("\n")
archivo.write(l)
archivo.write(j)
archivo.write(k)
archivo.write("\n")
archivo.write(m)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(n)
archivo.write("\n")
archivo.write(o)
archivo.write("\n")
archivo.write(p)
archivo.write("\n")
archivo.write(p)
archivo.write("\n")
archivo.write(q)
archivo.write(f)
archivo.write(g)
archivo.write(h)
archivo.write("\n")
archivo.write(r)
archivo.write("\n")
archivo.write(s)
archivo.write("\n")
archivo.write(t)
archivo.write("\n")
archivo.write(u)
archivo.write("\n")
archivo.write(w)
archivo.write("\n")
archivo.write(x)
archivo.write("\n")
archivo.write(y)
archivo.write("\n")
archivo.write(z)
archivo.write("\n")
archivo.write(hermano)
archivo.write("\n")
archivo.write(hermanodos)
archivo.write("\n")
archivo.write(hermanotres)
archivo.write("\n")
archivo.write(alturaDeLaCasa)
archivo.write("\n")
archivo.write(numero)
archivo.write("\n")
archivo.write(numeromadre)
archivo.write("\n")
archivo.write(numeropadre)
archivo.write("\n")
archivo.write(datos)
print("")
print("     ------------------------------------------------------")
print("          POST DOXXING > DatosWL > CRACKED > error4o4.org")
print("             https://www.facebook.com/error4o4.org")
print("     ------------------------------------------------------")
print("")
archivo.close()